version: '3.8'

services:
  mysqldb:
    image: arm64v8/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQLDB_HOST: mysqldb
      MYSQLDB_USER: myuser
      MYSQLDB_PASSWORD: mypassword
      MYSQLDB_DATABASE: mydatabase
      NODE_ENV: development
    depends_on:
      - mysqldb

volumes:
  mysql-data:
