replicaCount: 1

image:
  repository: amurillog/myapp
  pullPolicy: Always
  tag: "latest"

service:
  name: myapp
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  host: myapp.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

secrets:
  name: mysql-secrets
