name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm lint

      - name: Run tests
        run: npm test

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Build Docker image
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          VERSION=$(cat package.json | jq -r .version)
          docker build -t amurillog/myapp:$VERSION .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag amurillog/myapp:$VERSION amurillog/myapp:latest
          docker push amurillog/myapp:$VERSION
          docker push amurillog/myapp:latest

      - name: Trigger Helm Chart Update
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: amurillog26/helm-charts
          event-type: update-charts
          client-payload: '{"image_tag": "${{ steps.semantic.outputs.new_release_version }}"}'
